# Site settings
title: Voices
email: contact@sordina.net
description: >
  A place for ideas, reactions, etc.
  In the voices of the 12 common archetypes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sordina.github.io/"
github_username: sordina

# Build settings
markdown: kramdown
