title: Arrows
email: contact@sordina.net
url: "http://sordina.github.io/"
github_username: sordina
description: >
  Composition as Expression

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
exclude:
  - bak
  - themes
