# Site settings
title: Voices
email: contact@sordina.net
baseurl: ""
url: "http://sordina.github.io/"
github_username: sordina
description: A place for ideas, reactions, etc. In the voices of the 12 archetypes.

# Build settings
markdown: kramdown
exclude:
  - bak
  - themes
