title: Bows and Arrows
email: contact@sordina.net
url: "http://sordina.github.io/"
github_username: sordina
reddit: "https://www.reddit.com/r/sordina/"
# google_plus_username: "+LyndonMaydwell"
description: >
  Composition as Expression

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
exclude:
  - bak
  - themes
