# Site settings
title: Voices
email: contact@sordina.net
baseurl: ""
url: "http://sordina.github.io/"
github_username: sordina
description: >
  A place for ideas, reactions, etc. In the voices of
  <a href="http://www.soulcraft.co/essays/the_12_common_archetypes.html">The 12 Archetypes</a>.

# Build settings
markdown: kramdown
exclude:
  - bak
  - themes
