title: Bows and Arrows
email: contact@sordina.net
url: "http://sordina.github.io/"
github_username: sordina
reddit: "https://new.reddit.com/r/sordina/"
feed: "/feed.xml"
description: >
  Composition as Expression

# Build settings

markdown: kramdown
excerpt_separator: <!--more-->
exclude:
  - bak
  - themes

syntax-highlighting:
  enabled : true
  css: syntax.css
