---
version: "3.7"
services:
  blog:
    build: .
    volumes:
      - ./:/blog
    ports:
      - 4000:4000
    command:
      - jekyll
      - serve
      - --watch
      - --host=0.0.0.0

  new-post:
    image: alpine
    volumes:
      - ./:/blog
    # Requires NEW_POST variable be set to create a new post so that it doesn't come up with the other services
    entrypoint:
      - 'sh'
      - '-c'
      - |
          [ "$$NEW_POST" ] || exit 1
          read -p "New Blog-Post Title: " title
          [ "$$title" ] || exit 1
          filename=$$( echo `date +/blog/_posts/%Y-%m-%d-%s-$$(echo "$$title" | sed "s/[^a-zA-Z0-9]//g").markdown`)
          echo "$$filename"
          echo "---"                 > "$$filename"
          echo "layout: post"       >> "$$filename"
          echo "title: \"$$title\"" >> "$$filename"
          echo "categories: blog"   >> "$$filename"
          echo "reddit: false"      >> "$$filename"
          echo "---"                >> "$$filename"
    stdin_open: true
    tty: true

